### ISSUE TITLE
NullPointerException: Crash during Firebase Pre-launch report creation.

### ISSUE THREAD

**Issue by ravikumar-n** [joielechong/CountryCodePicker#48]
I have encountered this crash when Firebase ran it's automated tests for the uploaded Production apk. I'd tried to reproduce the crash manually, but unable to do so.

Here is the associated info related to crash:
Logcat:
```
04-03 09:56:57.424: I/Robo(11852): resource_name: "com.app.android:id/item_country_rly" with ActionParameters{}}.
04-03 09:56:57.433: I/Robo(11907): Espresso: performing single click on EspressoElement {# androidx.test.tools.crawler.proto.Rectangle@2ed4e7ff
04-03 09:56:57.433: I/Robo(11907): bottom: 602
04-03 09:56:57.433: I/Robo(11907): left: 88
04-03 09:56:57.433: I/Robo(11907): right: 632
04-03 09:56:57.433: I/Robo(11907): top: 598, # androidx.test.tools.crawler.proto.ElementDescription@385041b
04-03 09:56:57.433: I/Robo(11907): class_name: "android.widget.RelativeLayout"
04-03 09:56:57.433: I/Robo(11907): component_type: CONTAINER
04-03 09:56:57.433: I/Robo(11907): identifiers {
04-03 09:56:57.433: I/Robo(11907):   child_position: 3
04-03 09:56:57.433: I/Robo(11907):   mode_agnostic_sequence: "0.0.0.0.2.0"
04-03 09:56:57.433: I/Robo(11907):   mode_specific_sequence: "0.0.0.0.2.3"
04-03 09:56:57.433: I/Robo(11907): }
04-03 09:56:57.433: I/Robo(11907): input_type: NONE
04-03 09:56:57.433: I/Robo(11907): resource_name: "com.app.android:id/item_country_rly", # androidx.test.tools.crawler.proto.ElementState@485a255d
04-03 09:56:57.433: I/Robo(11907): capability: CLICK
04-03 09:56:57.433: I/Robo(11907): is_shown: true
04-03 09:56:57.433: I/Robo(11907): visible_bounds {
04-03 09:56:57.433: I/Robo(11907):   bottom: 602
04-03 09:56:57.433: I/Robo(11907):   left: 88
04-03 09:56:57.433: I/Robo(11907):   right: 632
04-03 09:56:57.433: I/Robo(11907):   top: 598
04-03 09:56:57.433: I/Robo(11907): }} with ActionParameters{}.
04-03 09:56:57.433: I/Robo(11907): [ 04-03 09:56:57.554 11907:11907 W/         ]
04-03 09:56:57.433: I/Robo(11907): Unable to open '/system/framework/prcui-config.jar': No such file or directory
04-03 09:56:57.554: W/art(11907): Failed to open zip archive '/system/framework/prcui-config.jar': I/O Error
04-03 09:56:57.573: I/Robo(11907): Rethrowing the exception thrown by the app.
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.rilixtech.a.c()' on a null object reference
	at com.rilixtech.CountryCodePicker.setSelectedCountry(CountryCodePicker.java:314)
	at com.rilixtech.CountryCodeDialog$ItemRecyclerViewClickListener.onItemClick(CountryCodeDialog.java:219)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3073)
	at android.widget.AbsListView$3.run(AbsListView.java:3910)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:164)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:156)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:136)
	at androidx.test.espresso.action.Tap$1.a(Tap.java:6)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```
Scenario:
![crash](https://user-images.githubusercontent.com/250998/55690091-709a8d00-59aa-11e9-85f9-87ffc883b112.gif)

**Comment by joielechong** [comment]
Thank you for the report! The problem is because the divider click is not handled and was considered as a valid item. The problem has been addressed with a33da8f2bf999a579272c7125a2ada7bc932baaa commit. Please try the 2.3.3 version. 

I'll close this issue for now, please reopen if the problem still persist.

**Comment by joielechong** [comment]
Thank you for the report! The problem is because the divider click is not handled and was considered as a valid item. The problem has been addressed with a33da8f2bf999a579272c7125a2ada7bc932baaa commit. Please try the 2.3.3 version. 

I'll close this issue for now, please reopen if the problem still persist.
